version: '3.4'

services:
  efsoft.customers.api:
    image: ${DOCKER_REGISTRY-}efsoftcustomersapi
    container_name: efsoft-services-customersapi
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: EFSoft.Customers.Api/Dockerfile
    environment:
      - ConnectionStrings__CustomersConnectionString=Data Source=CustomersDb;Initial Catalog=Customers;Integrated Security=False;User ID=sa;Password=Cacaoculapte12!;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    depends_on:
      - customersDb

  customersDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: efsoft-services-customersdb
    expose:
     - "1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Cacaoculapte12!
    ports:
     - "1433:1433"