apiVersion: apps/v1
kind: Deployment
metadata:
  name:  customers-deploy
  namespace: efsoft
  labels:
    app:  efsoft-customers
spec:
  selector:
    matchLabels:
      app: efsoft-customers
  #replicas: 1
  template:
    metadata:
      labels:
        app:  efsoft-customers
    spec:
      containers:
      - name:  efsoft-customers
        image:  emilfilip/efsoft_customers:9
        env:
        - name: ConnectionStrings__CustomersConnectionString
          value: "Server=192.168.132.162,1433;Database=Customers;User Id=sa;Password=Cacaoculapte12!;MultipleActiveResultSets=true;TrustServerCertificate=True;"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort:  8080
          name:  customers-port
---
      apiVersion: v1
      kind: Service
      metadata:
        name: customers-svc
        namespace: efsoft
      spec:
        selector:
          app: efsoft-customers
        type: ClusterIP
        ports:
        - name: customers-port
          port: 8094
          targetPort: 8080
# ---
#         apiVersion: v1
#         kind: Secret
#         metadata:
#           name: mssql-db-secret
#         type: Opaque
#         data:
#           username: c2E=    # base64 encoded "admin"
#           password: Q2FjYW9jdWxhcHRlMTIh # base64 encoded "password"